import {chromium} from 'playwright-core';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const raw=fs.readFileSync(new URL('./.env',import.meta.url),'utf8');
const env=Object.fromEntries(raw.split(/\r?\n/).filter(Boolean).map(s=>{const i=s.indexOf('=');return [s.slice(0,i),s.slice(i+1)]}));
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',args:['--no-first-run']});
const errors=[];
try{
 const page=await browser.newPage({viewport:{width:1440,height:900},locale:'ar-EG'});
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
 await page.getByText('رحلتك نحو').waitFor();
 await page.screenshot({path:fileURLToPath(new URL('./qa-desktop.png',import.meta.url))});
 console.log('PASS: desktop home renders');
 await page.goto('http://127.0.0.1:5173/login');
 await page.locator('input[type=email]').fill(env.DEMO_STUDENT_EMAIL);
 await page.locator('input[type=password]').fill(env.DEMO_STUDENT_PASSWORD);
 await page.locator('button[type=submit]').click();
 await page.getByText('نظرة عامة').waitFor();
 await page.screenshot({path:fileURLToPath(new URL('./qa-dashboard.png',import.meta.url))});
 console.log('PASS: student login and dashboard render');
 const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,locale:'ar-EG',isMobile:true,hasTouch:true});
 mobile.on('pageerror',e=>errors.push(e.message));
 await mobile.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
 await mobile.getByText('رحلتك نحو').waitFor();
 const overflow=await mobile.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+2);
 await mobile.screenshot({path:fileURLToPath(new URL('./qa-mobile.png',import.meta.url))});
 console.log('MOBILE_OVERFLOW='+overflow);
 if(errors.length)throw Error(errors.join('; '));
 console.log('PASS: no browser JavaScript errors');
 const instructor=await browser.newPage({viewport:{width:1366,height:900},locale:'ar-EG'});
 instructor.on('pageerror',e=>errors.push(e.message));
 await instructor.goto('http://127.0.0.1:5173/login');
 await instructor.locator('input[type=email]').fill(env.DEMO_TEACHER_EMAIL);
 await instructor.locator('input[type=password]').fill(env.DEMO_TEACHER_PASSWORD);
 await instructor.locator('button[type=submit]').click();
 await instructor.getByRole('button',{name:'سجل الحضور'}).click();
 await instructor.getByText('تقرير حضور الطلاب').waitFor();
 await instructor.screenshot({path:fileURLToPath(new URL('./qa-attendance.png',import.meta.url))});
 if(errors.length)throw Error(errors.join('; '));
 console.log('PASS: teacher attendance report loads without browser errors');
}finally{await browser.close()}
