import fs from 'node:fs';
import assert from 'node:assert/strict';
const entries=fs.readFileSync(new URL('./.env',import.meta.url),'utf8').split(/\r?\n/).filter(Boolean).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)]);
const cfg=Object.fromEntries(entries);
const request=async(path,opts={})=>{const r=await fetch('http://127.0.0.1:4010/api'+path,opts);return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]}};
const login=async(role)=>request('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:cfg['DEMO_'+role+'_EMAIL']||cfg.ADMIN_EMAIL,password:cfg['DEMO_'+role+'_PASSWORD']||cfg.ADMIN_PASSWORD})});
const student=await login('STUDENT');
assert.equal(student.status,200);
assert.equal(student.data.user.role,'student');
const teacher=await login('TEACHER');
assert.equal(teacher.status,200);
const admin=await login('ADMIN');
assert.equal(admin.status,200);
const summary=await request('/my/overview',{headers:{Cookie:student.cookie}});
assert.equal(summary.status,200);
assert.ok(summary.data.courses.length>0);
const users=await request('/admin/users',{headers:{Cookie:student.cookie}});
assert.equal(users.status,403);
const usersAsAdmin=await request('/admin/users',{headers:{Cookie:admin.cookie}});
assert.equal(usersAsAdmin.status,200);
console.log('PASS: 3 role logins, dashboard, student isolation, admin users');
