import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import bcrypt from 'bcryptjs';
import {AccessToken} from 'livekit-server-sdk';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'madrasati-test-'));
process.env.MADRASATI_DB_PATH = path.join(tmp, 'isolated.sqlite');
const { db, run, get, uid, now } = await import('../server/db.js');
const email = 'student@test.local';
const password = crypto.randomBytes(18).toString('hex');
const pwdHash = bcrypt.hashSync(password, 10);
function addUser(role, name, address, status='active') {
 const id = uid();
 run('INSERT INTO users(id,name,email,password_hash,role,status,created_at) VALUES(?,?,?,?,?,?,?)',id,name,address,pwdHash,role,status,now());
 return id;
}
const admin = addUser('admin','Test Admin','admin@test.local');
const teacher = addUser('teacher','Test Teacher','teacher@test.local');
const student = addUser('student','Test Student',email);
const outsider = addUser('student','Another Student','outsider@test.local');
const teacherTwo = addUser('teacher','Teacher Two','teacher2@test.local');
const course = uid();
run('INSERT INTO courses(id,title,description,subject,level,price,duration_minutes,capacity,teacher_id,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)',course,'اختبار الرياضيات','دورة للاختبارات الآلية','رياضيات','الإعدادي',0,60,1,teacher,'published',now());
const lesson = uid();
run('INSERT INTO lessons(id,course_id,title,starts_at,duration_minutes,status,room_key,created_at) VALUES(?,?,?,?,?,?,?,?)',lesson,course,'حصة اختبار',new Date(Date.now()+60*1000).toISOString(),60,'scheduled',uid(),now());
const futureLesson = uid();
run('INSERT INTO lessons(id,course_id,title,starts_at,duration_minutes,status,room_key,created_at) VALUES(?,?,?,?,?,?,?,?)',futureLesson,course,'حصة بعد أسبوع',new Date(Date.now()+7*86400000).toISOString(),60,'scheduled',uid(),now());
db.close();
const port = await new Promise((resolve,reject) => {
 const s=net.createServer();
 s.once('error',reject);
 s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});
});
const secret = crypto.randomBytes(40).toString('hex');
const liveSecret = crypto.randomBytes(32).toString('hex');
const server = spawn(process.execPath,['server/index.js'],{cwd:root,windowsHide:true,env:{...process.env,PORT:String(port),JWT_SECRET:secret,TEST_EMAIL_CAPTURE_DIR:path.join(tmp,'emails'),APP_ORIGIN:'http://127.0.0.1:'+port,LIVEKIT_URL:'wss://test.livekit.cloud',LIVEKIT_API_KEY:'testkey',LIVEKIT_API_SECRET:liveSecret}});
let logs='';
server.stdout.on('data', x=>logs+=x.toString());
server.stderr.on('data', x=>logs+=x.toString());
const base = 'http://127.0.0.1:'+port+'/api';
async function request(url, method='GET', body, cookie) {
 const res = await fetch(base+url,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(cookie?{'Cookie':cookie}:{})},body:body?JSON.stringify(body):undefined});
 let data;
 try { data=await res.json(); } catch { data={}; }
 return {status:res.status,data,cookie:res.headers.get('set-cookie')?.split(';')[0]};
}
let passed=0;
function check(condition, label) { assert.ok(condition,label);passed++; console.log('PASS '+label); }
async function login(address) {
 const res=await request('/auth/login','POST',{email:address,password});
 check(res.status===200&&res.cookie,'login '+address.split('@')[0]);
 return res.cookie;
}
try {
 let ready=false;
 for(let i=0;i<80;i++){
  if(server.exitCode!==null) throw Error('Server failed: '+logs);
  await new Promise(r=>setTimeout(r,100));
  try { if((await request('/health')).status===200){ready=true;break;} } catch {}
 }
 check(ready,'server is healthy');
 const cookies = {admin:await login('admin@test.local'),teacher:await login('teacher@test.local'),student:await login(email),outsider:await login('outsider@test.local'),teacherTwo:await login('teacher2@test.local')};
 let profileResponsesOk=true;
 for(let i=0;i<35;i++){if((await request('/auth/me','GET',null,cookies.teacher)).status!==200){profileResponsesOk=false;break;}}
 check(profileResponsesOk,'profile checks do not consume login rate limit');
 check((await request('/my/overview')).status===401,'unauthenticated dashboard denied');
 check((await request('/a-route-that-does-not-exist')).status===404,'unknown API route returns JSON 404');
 check((await request('/courses')).data.courses.length===1,'published course visible');
 check((await request('/lessons/'+lesson,'GET',null,cookies.outsider)).status===403,'outsider cannot view lesson');
 check((await request('/lessons/'+lesson+'/token','POST',{},cookies.outsider)).status===403,'outsider cannot request video token');
 check((await request('/courses','POST',{title:'X',description:'Y',subject:'Z',level:'P'},cookies.student)).status===403,'student cannot create course');
 check((await request('/courses/'+course+'/lessons','POST',{title:'X',starts_at:new Date().toISOString()},cookies.teacherTwo)).status===403,'unrelated teacher cannot create lesson');
 check((await request('/courses/'+course+'/book','POST',{},cookies.student)).status===201,'student booking submitted');
 check((await request('/courses/'+course+'/book','POST',{},cookies.student)).status===409,'duplicate booking denied');
 check((await request('/lessons/'+lesson,'GET',null,cookies.student)).status===403,'pending booking cannot view lesson');
 const overview=(await request('/my/overview','GET',null,cookies.teacher)).data;
 const booking=overview.bookings.find(b=>b.course_id===course);
 check(booking?.status==='pending','teacher sees pending booking');
 check((await request('/bookings/'+booking.id,'PATCH',{status:'approved'},cookies.teacherTwo)).status===403,'unrelated teacher cannot approve');
 check((await request('/bookings/'+booking.id,'PATCH',{status:'approved'},cookies.teacher)).status===200,'teacher approves booking');
 check((await request('/lessons/'+lesson,'GET',null,cookies.student)).status===200,'approved student can view lesson');
 check((await request('/lessons/'+futureLesson+'/token','POST',{},cookies.student)).status===403,'early video entry blocked');
 check((await request('/lessons/'+lesson+'/classroom','GET',null,cookies.outsider)).status===403,'unapproved student cannot view room moderation state');
 check((await request('/lessons/'+lesson+'/moderate','POST',{action:'mute_all'},cookies.student)).status===403,'student cannot mute other participants');
 check((await request('/lessons/'+lesson+'/moderate','POST',{action:'mute_all'},cookies.teacherTwo)).status===403,'unrelated teacher cannot moderate class');
 const waitingRoom=await request('/lessons/'+lesson+'/classroom','GET',null,cookies.student);
 check(waitingRoom.status===200&&waitingRoom.data.speakerMode===''&&waitingRoom.data.handRaised===false,'student begins in listen-only classroom mode');
 check((await request('/lessons/'+lesson+'/hand','POST',{raised:'yes'},cookies.student)).status===400,'invalid raise hand payload is rejected');
 check((await request('/lessons/'+lesson+'/hand','POST',{raised:true},cookies.outsider)).status===403,'only approved students may raise a hand');
 check((await request('/lessons/'+lesson+'/hand','POST',{raised:true},cookies.student)).status===200,'student can raise a hand');
 const teacherRoom=await request('/lessons/'+lesson+'/classroom','GET',null,cookies.teacher);
 check(teacherRoom.status===200&&teacherRoom.data.hands.some(h=>h.student_id===student),'teacher sees student hand raise');
 check((await request('/lessons/'+lesson+'/classroom','GET',null,cookies.teacherTwo)).status===403,'unrelated teacher cannot see hand raise list');
 check((await request('/lessons/'+lesson+'/moderate','POST',{action:'clear_hand',student_id:student},cookies.teacher)).status===200,'teacher clears hand raise');
 check((await request('/lessons/'+lesson+'/classroom','GET',null,cookies.student)).data.handRaised===false,'student hand state updates after moderation');
 check((await request('/lessons/'+lesson+'/moderate','POST',{action:'not_real'},cookies.teacher)).status===400,'unknown moderator action rejected');
 const studentJoin=await request('/lessons/'+lesson+'/token','POST',{},cookies.student);
 check(studentJoin.status===200&&!!studentJoin.data.token,'approved student issued video token');
 const studentGrant=JSON.parse(Buffer.from(studentJoin.data.token.split('.')[1],'base64url').toString());
 check(studentGrant.video?.canPublish===false&&studentGrant.video?.canSubscribe===true&&studentGrant.video?.canPublishData===false,'student joins as subscriber without microphone or camera privileges');
 const teacherJoin=await request('/lessons/'+lesson+'/token','POST',{},cookies.teacher);
 check(teacherJoin.status===200&&!!teacherJoin.data.token,'teacher issued video token');
 const teacherGrant=JSON.parse(Buffer.from(teacherJoin.data.token.split('.')[1],'base64url').toString());
 check(teacherGrant.video?.canPublish===true&&teacherGrant.video?.roomAdmin===true,'teacher can broadcast and moderate the room');
 const attendanceBefore=await request('/courses/'+course+'/attendance','GET',null,cookies.teacher);
 check(attendanceBefore.status===200&&attendanceBefore.data.attendance.length===0,'video token alone does not count as attendance');
 check((await request('/courses/'+course+'/attendance','GET',null,cookies.outsider)).status===403,'attendance list restricted to teacher and admin');
 const unsigned=await fetch(base+'/webhooks/livekit',{method:'POST',headers:{'Content-Type':'application/webhook+json'},body:JSON.stringify({event:'participant_joined'})});
 check(unsigned.status===401,'unsigned attendance webhook is rejected');
 const body=JSON.stringify({event:'participant_joined',createdAt:Math.floor(Date.now()/1000),id:uid(),room:{name:studentGrant.video.room},participant:{identity:student,name:'Test Student'}});
 const signed=new AccessToken('testkey',liveSecret);
 signed.sha256=crypto.createHash('sha256').update(body).digest('base64');
 const signedResult=await fetch(base+'/webhooks/livekit',{method:'POST',headers:{'Content-Type':'application/webhook+json','Authorization':await signed.toJwt()},body});
 check(signedResult.status===200,'valid signed LiveKit webhook accepted');
 const recorded=await request('/courses/'+course+'/attendance','GET',null,cookies.teacher);
 check(recorded.data.attendance.some(x=>x.user_id===student&&x.lesson_id===lesson),'actual participant join recorded in attendance');
 const extraBooking=await request('/courses/'+course+'/book','POST',{},cookies.outsider);
 check(extraBooking.status===409,'full course rejects additional reservation');
 check((await request('/auth/register','POST',{name:'Unsafe admin',email:'unsafe'+uid()+'@test.local',password,role:'admin'})).status===403,'public registration cannot create admin accounts');
 check((await request('/auth/register','POST',{name:'Unsafe teacher',email:'unsafe-teacher'+uid()+'@test.local',password,role:'teacher'})).status===403,'public registration cannot create teacher accounts');
 const testStudentEmail='verified'+uid()+'@test.local';
 const reg=await request('/auth/register','POST',{name:'طالبة جديدة',email:testStudentEmail,password,role:'student',guardian_email:'guardian@example.com'});
 check(reg.status===201&&reg.data.pending===true,'email-based student signup requires verification');
 const {DatabaseSync}=await import('node:sqlite');
 const inspected=new DatabaseSync(process.env.MADRASATI_DB_PATH,{readOnly:true});
 const pendingUser=inspected.prepare('SELECT id,status,email_verified_at,guardian_email FROM users WHERE email=?').get(testStudentEmail);
 inspected.close();
 check(pendingUser?.status==='pending'&&!pendingUser.email_verified_at&&pendingUser.guardian_email==='guardian@example.com','student pending until email verification');
 check((await request('/auth/login','POST',{email:testStudentEmail,password})).status===403,'unverified student cannot log in');
 const mailbox=path.join(tmp,'emails');
 const files=fs.readdirSync(mailbox).filter(f=>f.endsWith('verify_email.txt'));
 check(files.length===1,'verification email captured by local-only mail preview');
 const letter=fs.readFileSync(path.join(mailbox,files[0]),'utf8');
 const token=letter.match(/token=([a-f0-9]{64})/)?.[1];
 check(Boolean(token),'email contains one-time verification link');
 check((await request('/auth/verify-email','POST',{token:'a'.repeat(64)})).status===400,'invalid verification token rejected');
 check((await request('/auth/verify-email','POST',{token})).status===200,'email verification activates student');
 check((await request('/auth/verify-email','POST',{token})).status===400,'verification token cannot be reused');
 const verifiedCookie=await login(testStudentEmail);
 check(!!verifiedCookie,'verified student can log in');
 check((await request('/auth/forgot-password','POST',{email:testStudentEmail})).status===200,'student can request password reset email');
 const resetFile=fs.readdirSync(mailbox).filter(f=>f.endsWith('reset_password.txt'))[0];
 const resetToken=fs.readFileSync(path.join(mailbox,resetFile),'utf8').match(/token=([a-f0-9]{64})/)?.[1];
 check(Boolean(resetToken),'reset email contains a one-time reset token');
 const newPass=crypto.randomBytes(17).toString('hex');
 check((await request('/auth/reset-password','POST',{token:resetToken,password:newPass})).status===200,'password reset succeeds');
 check((await request('/auth/me','GET',null,verifiedCookie)).status===401,'reset revokes existing login session');
 check((await request('/auth/reset-password','POST',{token:resetToken,password:newPass})).status===400,'reset link cannot be reused');
 check((await request('/auth/login','POST',{email:testStudentEmail,password:newPass})).status===200,'new password works');
 check((await request('/admin/users','GET',null,cookies.student)).status===403,'student cannot view admin users');
 const users=(await request('/admin/users','GET',null,cookies.admin)).data.users;
 check(users.some(u=>u.role==='student'&&u.email===testStudentEmail&&u.status==='active'),'admin sees verified student');
 const adminCreated=await request('/courses','POST',{title:'دورة مدير',description:'فصل تعليمي للاختبار',subject:'أحياء',level:'الثانوي',price:0,capacity:20,duration_minutes:60,teacher_id:teacherTwo},cookies.admin);
 check(adminCreated.status===201&&!!adminCreated.data.id,'admin assigns a course to selected teacher');
 const teacherTwoCourses=(await request('/my/overview','GET',null,cookies.teacherTwo)).data.courses;
 check(teacherTwoCourses.some(c=>c.id===adminCreated.data.id),'assigned teacher sees their new course');
 const patch={title:'رياضيات متقدمة',description:'تفاصيل محدثة',subject:'رياضيات',level:'الثانوي',price:0,capacity:1,duration_minutes:90};
 check((await request('/courses/'+course,'PATCH',patch,cookies.student)).status===403,'student cannot edit course');
 check((await request('/courses/'+course,'PATCH',patch,cookies.teacherTwo)).status===403,'unrelated teacher cannot edit course');
 check((await request('/courses/'+course,'PATCH',{capacity:0},cookies.teacher)).status===400,'invalid capacity rejected');
 check((await request('/courses/'+course,'PATCH',{price:100},cookies.teacher)).status===409,'approved free students cannot be silently converted into paid subscriptions');
 check((await request('/courses/'+course,'PATCH',patch,cookies.teacher)).status===200,'teacher updates owned course');
 const updated=(await request('/courses/'+course)).data.course;
 check(updated.title===patch.title&&updated.price===0&&updated.capacity===1,'course update persisted');
 check((await request('/courses/'+course,'PATCH',{teacher_id:teacherTwo},cookies.teacher)).status===403,'teacher cannot reassign course');
 check((await request('/lessons/'+futureLesson,'PATCH',{title:'اختراق'},cookies.teacherTwo)).status===403,'unrelated teacher cannot edit lesson');
 check((await request('/lessons/'+futureLesson,'PATCH',{starts_at:'invalid'},cookies.teacher)).status===400,'invalid lesson date rejected');
 check((await request('/lessons/'+futureLesson,'PATCH',{meet_url:'https://meet.google.com/abc-defg-hij'},cookies.teacher)).status===400,'external meeting links cannot override the internal LiveKit room');
 check((await request('/courses/'+course+'/lessons','POST',{title:'External meeting attempt',starts_at:new Date(Date.now()+9*86400000).toISOString(),meet_url:'https://meet.google.com/abc-defg-hij'},cookies.teacher)).status===400,'new classes never accept external Google Meet links');
 const changedDate=new Date(Date.now()+8*86400000).toISOString();
 check((await request('/lessons/'+futureLesson,'PATCH',{title:'حصة مؤجلة',starts_at:changedDate,duration_minutes:75},cookies.teacher)).status===200,'teacher reschedules future lesson');
 const changedLesson=(await request('/lessons/'+futureLesson,'GET',null,cookies.teacher)).data.lesson;
 check(changedLesson.title==='حصة مؤجلة'&&changedLesson.starts_at===changedDate,'lesson schedule update persisted');
 check((await request('/courses/'+course,'PATCH',{capacity:-1},cookies.admin)).status===400,'admin invalid edit rejected');
 const adminDashboard=await request('/admin/dashboard','GET',null,cookies.admin);
 check(adminDashboard.status===200&&adminDashboard.data.statistics.students>=2,'admin dashboard returns real summary');
 check((await request('/admin/dashboard','GET',null,cookies.student)).status===403,'student cannot view admin dashboard');
 check((await request('/admin/dashboard','GET',null,cookies.teacher)).status===403,'teacher cannot view admin dashboard');
 const studentDashboard=await request('/student/dashboard','GET',null,cookies.student);
 check(studentDashboard.status===200&&studentDashboard.data.learning.some(c=>c.id===course),'student dashboard lists enrolled courses');
 check((await request('/student/dashboard','GET',null,cookies.admin)).status===403,'admin cannot access student dashboard endpoint');
 check((await request('/student/dashboard','GET',null,cookies.outsider)).data.learning.length===0,'unenrolled student sees no protected course');
 const changedProfile=await request('/my/profile','PATCH',{name:'Updated Student'},cookies.student);
 check(changedProfile.status===200&&changedProfile.data.user.name==='Updated Student','student updates own display name');
 check((await request('/my/profile','PATCH',{name:''},cookies.student)).status===400,'empty profile name is rejected');
 check((await request('/admin/dashboard')).status===401,'anonymous visitor cannot access admin statistics');
 console.log('RESULT '+passed+' integration checks passed.');
} finally {
 server.kill();
 await new Promise(resolve=>server.once('exit',resolve)).catch(()=>{});
 await new Promise(r=>setTimeout(r,150));
 fs.rmSync(tmp,{recursive:true,force:true,maxRetries:5,retryDelay:100});
}
