import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=file=>readFileSync(new URL('../'+file,import.meta.url),'utf8');
const html=read('index.html'),robots=read('public/robots.txt'),sitemap=read('public/sitemap.xml');
assert.match(html,/<title>مس صوفيا للعلوم/,'Arabic school identity in title');
assert.match(html,/<link rel="canonical" href="https:\/\/mssofia.pages.dev\/"/);
assert.match(html,/<meta name="description" content="مس صوفيا للعلوم/);
const json=html.match(/<script type="application\/ld\+json">\s*([\s\S]*?)<\/script>/)?.[1];
assert.ok(json,'structured data present');
const entity=JSON.parse(json);
assert.equal(entity['@type'],'EducationalOrganization');
assert.equal(entity.name,'مس صوفيا للعلوم');
assert.match(robots,/Disallow: \/api\//);
assert.match(robots,/Disallow: \/lesson\//);
assert.match(robots,/Sitemap: https:\/\/mssofia.pages.dev\/sitemap.xml/);
for(const route of ['/', '/courses','/terms','/privacy'])assert.ok(sitemap.includes('<loc>https://mssofia.pages.dev'+route+'</loc>'),'sitemap '+route);
const verification=read('public/google15827c2f4246bb08.html');
assert.equal(verification.trim(),'google-site-verification: google15827c2f4246bb08.html','original Google ownership file is published without altered content');
const brand=read('src/components/MrsSofiaBrand.jsx');
assert.match(brand,/مس صوفيا للعلوم/);
console.log('PASS school indexing metadata, sitemap and original Google verification file (no ranking promise)');
