import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {LayoutDashboard,BookOpen,CalendarDays,ClipboardList,UserRound,GraduationCap,Video,CheckCircle2,Clock3,ArrowLeft,TrendingUp,PlayCircle,Save} from 'lucide-react';
import PortalShell,{Metric,PanelEmpty,PanelHeading,StatusPill,dateTimeLabel} from '../components/PortalShell.jsx';
const api=async(path,opts={})=>{const r=await fetch('/api'+path,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...opts});const d=await r.json();if(!r.ok)throw Error(d.error||'حدث خطأ');return d};
export default function StudentPortal({user,setUser,show}){
 const [tab,setTab]=useState('overview'),[data,setData]=useState(null),[learning,setLearning]=useState(null),[error,setError]=useState(''),[name,setName]=useState(user.name),[busy,setBusy]=useState(false);
 const load=()=>Promise.all([api('/my/overview'),api('/student/dashboard')]).then(([overview,extra])=>{setData(overview);setLearning(extra);setError('')}).catch(e=>setError(e.message));
 useEffect(()=>{load()},[]);
 const bookings=data?.bookings||[],lessons=data?.lessons||[],courses=learning?.learning||[],attendance=new Set(learning?.attendedLessonIds||[]);
 const upcoming=lessons.filter(x=>Date.parse(x.starts_at)+x.duration_minutes*60000>Date.now()).sort((a,b)=>Date.parse(a.starts_at)-Date.parse(b.starts_at));
 const pending=bookings.filter(x=>x.status==='pending').length,attended=courses.reduce((n,c)=>n+c.attended_lessons,0),total=courses.reduce((n,c)=>n+c.total_lessons,0);
 const nav=[{id:'overview',label:'الرئيسية',icon:LayoutDashboard},{id:'courses',label:'دوراتي',icon:BookOpen},{id:'schedule',label:'جدول الحصص',icon:CalendarDays},{id:'bookings',label:'طلباتي',icon:ClipboardList,count:pending},{id:'profile',label:'الملف الشخصي',icon:UserRound}];
 const headings={overview:'رحلتك التعليمية تبدأ من هنا',courses:'دوراتي التعليمية',schedule:'جدول حصصي',bookings:'متابعة طلبات الحجز',profile:'ملفي الشخصي'};
 const subtitle={overview:'كل ما تحتاجه لمتابعة تقدمك الدراسي في مكان واحد.',courses:'دوراتك المقبولة ومؤشرات حضورك وتقدمك.',schedule:'اطّلع على مواعيد حصصك وادخل الفصل عند إتاحته.',bookings:'اعرف حالة كل طلب قدمته للالتحاق بالدورات.',profile:'تحكم في بيانات حسابك الأساسية.'};
 const courseCards=<div className="portal-course-grid">{courses.map(c=><article className="portal-course" key={c.id}><div className="portal-course-art"><GraduationCap size={36}/><span>{c.subject}</span></div><div className="portal-course-body"><small>{c.level} • أ. {c.teacher_name}</small><h3>{c.title}</h3><div className="portal-progress-label"><span>الحصص التي حضرتها</span><b>{c.attended_lessons} / {c.total_lessons}</b></div><div className="portal-progress"><span style={{width:Math.min(100,c.total_lessons?c.attended_lessons/c.total_lessons*100:0)+'%'}}/></div><div className="portal-course-footer"><Link to={'/courses/'+c.id}>تفاصيل الدورة <ArrowLeft size={15}/></Link>{c.next_lesson_at&&<small>{dateTimeLabel(c.next_lesson_at)}</small>}</div></div></article>)}</div>;
 const lessonRows=(items)=>items.length?<div className="portal-list">{items.map(l=><div className="portal-list-item" key={l.id}><span className="portal-list-icon"><Video size={20}/></span><div className="portal-list-copy"><strong>{l.title}</strong><small>{l.course_title} • {dateTimeLabel(l.starts_at)}</small></div><div className="portal-list-action">{attendance.has(l.id)?<span className="portal-attended"><CheckCircle2 size={15}/> تم الحضور</span>:null}<Link className="portal-soft-btn" to={'/lesson/'+l.id}>غرفة الحصة <ArrowLeft size={15}/></Link></div></div>)}</div>:<PanelEmpty title="لا توجد حصص بعد" description="الحصص القادمة لدوراتك المقبولة ستظهر هنا" icon={CalendarDays}/>;
 const bookingRows=bookings.length?<div className="portal-list">{bookings.map(b=><div className="portal-list-item" key={b.id}><span className="portal-list-icon"><BookOpen size={20}/></span><div className="portal-list-copy"><strong>{b.course_title}</strong><small>أ. {b.teacher_name} • طلب الالتحاق</small></div><StatusPill status={b.status}/></div>)}</div>:<PanelEmpty title="لم تقدم طلبات بعد" description="استكشف الدورات واطلب الانضمام إلى الدورة المناسبة"/>;
 return <PortalShell variant="student" user={user} nav={nav} active={tab} onNavigate={setTab} title={headings[tab]} subtitle={subtitle[tab]} toolbar={<Link className="portal-primary-btn" to="/courses"><BookOpen size={17}/> استكشف الدورات</Link>}>
 {error&&<div role="alert" className="portal-alert">{error}<button onClick={load}>إعادة المحاولة</button></div>}
 {!data||!learning?<div className="portal-loading">جارٍ تجهيز مساحة التعلم...</div>:<>
 {tab==='overview'&&<><div className="portal-welcome"><div><span>أهلاً بك من جديد ✨</span><h2>{user.name.split(' ')[0]}، جاهز لتحقيق إنجاز جديد؟</h2><p>كل حصة تحضرها تقربك من هدفك. تابع جدولك وابدأ رحلتك بثقة.</p><button onClick={()=>setTab('schedule')}>عرض جدول الحصص <ArrowLeft size={17}/></button></div><span className="portal-welcome-symbol"><GraduationCap size={94}/></span></div><div className="portal-metrics"><Metric icon={BookOpen} label="الدورات المسجلة" value={courses.length} sub="دورات تم قبولك بها"/><Metric icon={CalendarDays} label="الحصص القادمة" value={upcoming.length} sub="في جدولك الدراسي" tone="blue"/><Metric icon={CheckCircle2} label="الحصص التي حضرتها" value={attended} sub={total?'من أصل '+total+' حصص':'ابدأ الحضور لتحقيق تقدم'} tone="green"/><Metric icon={Clock3} label="طلبات قيد الانتظار" value={pending} sub="في انتظار موافقة المعلم" tone="orange"/></div><div className="portal-two-col"><section className="portal-panel"><PanelHeading title="أقرب الحصص" description="مواعيدك القادمة" action={<button className="portal-text-button" onClick={()=>setTab('schedule')}>كل الحصص <ArrowLeft size={15}/></button>}/>{lessonRows(upcoming.slice(0,4))}</section><section className="portal-panel"><PanelHeading title="طلبات الالتحاق" description="آخر التحديثات على حجوزاتك" action={<button className="portal-text-button" onClick={()=>setTab('bookings')}>عرض الكل <ArrowLeft size={15}/></button>}/>{bookingRows}</section></div></>}
 {tab==='courses'&&<section className="portal-panel"><PanelHeading title="الدورات المسجلة" description="مؤشر التقدم يعتمد على تسجيل الحضور الفعلي"/>{courses.length?courseCards:<PanelEmpty title="لم تنضم لدورة حتى الآن" description="ابدأ باكتشاف الدورات المتاحة واختيار المناسب"/>}</section>}
 {tab==='schedule'&&<section className="portal-panel"><PanelHeading title="قائمة الحصص" description="عرض مواعيد الحصص المقبولة من الأقدم للأحدث"/>{lessonRows(lessons)}</section>}
 {tab==='bookings'&&<section className="portal-panel"><PanelHeading title="جميع الطلبات" description="حالة الموافقة تحدد إمكانية دخول الحصص"/>{bookingRows}</section>}
 {tab==='profile'&&<section className="portal-panel portal-form-panel"><PanelHeading title="بيانات الحساب" description="يمكنك تغيير اسم العرض هنا. البريد الإلكتروني ثابت حالياً."/><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await api('/my/profile',{method:'PATCH',body:JSON.stringify({name})});setUser(r.user);show('تم تحديث بيانات الحساب')}catch(err){setError(err.message)}finally{setBusy(false)}}}><label>الاسم بالكامل<input value={name} maxLength={80} required onChange={e=>setName(e.target.value)}/></label><label>البريد الإلكتروني<input value={user.email} disabled readOnly/></label><label>نوع الحساب<input value="طالب" disabled readOnly/></label><button className="portal-primary-btn" disabled={busy} type="submit"><Save size={17}/>{busy?'جارٍ الحفظ...':'حفظ التغييرات'}</button></form></section>}
 </>}
 </PortalShell>
}
