import React,{useEffect,useMemo,useState,lazy,Suspense} from 'react';
import {Link} from 'react-router-dom';
import {LayoutDashboard,BookOpen,CalendarDays,Users,ClipboardList,CheckCircle2,Clock3,Plus,Save,Search,ArrowLeft,GraduationCap,Video,Presentation,UserRound,Mail,Eye,Edit3} from 'lucide-react';
import PortalShell,{Metric,PanelEmpty,PanelHeading,StatusPill,dateTimeLabel} from '../components/PortalShell.jsx';
const AttendancePanel=lazy(()=>import('../components/AttendancePanel.jsx'));
const json=async(path,options={})=>{
 const response=await fetch('/api'+path,{credentials:'same-origin',headers:{'Content-Type':'application/json'},...options});
 const data=await response.json().catch(()=>({}));
 if(!response.ok)throw Error(data.error||'تعذر تنفيذ العملية');
 return data;
};
const fields={title:'',description:'',subject:'علوم',level:'الإعدادي',capacity:20,price:0,duration_minutes:60};
const toLocal=iso=>{const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const newLesson=(course)=>({course_id:course.id,title:'',starts_at:'',duration_minutes:course.duration_minutes});
export default function TeacherPortal({user,setUser,show}){
 const [tab,setTab]=useState('overview'),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(''),[form,setForm]=useState({}),[name,setName]=useState(user.name),[search,setSearch]=useState('');
 const load=async()=>{try{const result=await json('/my/overview');setData(result);setError('')}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[]);
 const courses=data?.courses||[],bookings=data?.bookings||[],lessons=data?.lessons||[];
 const pending=bookings.filter(b=>b.status==='pending'),approved=bookings.filter(b=>b.status==='approved');
 const studentCount=new Set(approved.map(b=>b.student_id)).size;
 const upcoming=lessons.filter(l=>l.status==='scheduled'&&Date.parse(l.starts_at)+l.duration_minutes*60000>Date.now()).sort((a,b)=>Date.parse(a.starts_at)-Date.parse(b.starts_at));
 const studentBookings=approved.filter(b=>[b.student_name,b.student_email,b.course_title].some(s=>String(s||'').toLowerCase().includes(search.trim().toLowerCase())));
 const nav=[{id:'overview',label:'نظرة عامة',icon:LayoutDashboard},{id:'courses',label:'دوراتي',icon:BookOpen},{id:'students',label:'طلابي',icon:Users},{id:'bookings',label:'طلبات الحجز',icon:ClipboardList,count:pending.length},{id:'schedule',label:'جدول الحصص',icon:CalendarDays},{id:'attendance',label:'سجل الحضور',icon:CheckCircle2},{id:'profile',label:'ملفي الشخصي',icon:UserRound}];
 const labels={overview:'مرحباً بك في لوحة المعلم',courses:'إدارة الكورسات',students:'الطلاب المسجلون',bookings:'طلبات التسجيل',schedule:'جدول الحصص',attendance:'تقارير الحضور',profile:'بيانات حساب المعلم'};
 const descriptions={overview:'تابع الكورسات والحصص وطلبات الطلاب من مكان واحد.',courses:'أنشئ كورسات العلوم وعدّل محتواها وحدد مواعيد الحصص.',students:'راجع بيانات طلابك المقبولين في الدورات الخاصة بك.',bookings:'راجع طلبات الالتحاق ووافق أو ارفض حسب الأماكن المتاحة.',schedule:'نظّم مواعيد الدروس وادخل الفصول المباشرة.',attendance:'تقرير حضور الطلاب الفعلي المسجل في الفصول.',profile:'حدّث اسمك الظاهر للطلاب في الدورات والحصص.'};
 const act=async(path,method,body)=>{setBusy(true);setError('');try{await json(path,{method,body:JSON.stringify(body)});setModal('');setForm({});show('تم حفظ التغييرات بنجاح');await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const bookingView=(items)=>items.length?<div className="portal-list">{items.map(b=><div className="portal-list-item" key={b.id}><span className="portal-list-icon"><Users size={18}/></span><div className="portal-list-copy"><strong>{b.student_name}</strong><small>{b.course_title} • {b.student_email}</small></div><StatusPill status={b.status}/>{b.status==='pending'&&<div className="portal-list-action"><button className="portal-soft-btn" disabled={busy} onClick={()=>act('/bookings/'+b.id,'PATCH',{status:'approved'})}>موافقة</button><button className="portal-soft-btn danger" disabled={busy} onClick={()=>act('/bookings/'+b.id,'PATCH',{status:'rejected'})}>رفض</button></div>}</div>)}</div>:<PanelEmpty title="لا توجد طلبات حالياً" description="طلبات الانضمام لدوراتك ستظهر هنا"/>;
 const lessonView=(items)=>items.length?<div className="portal-list">{items.map(l=><div className="portal-list-item" key={l.id}><span className="portal-list-icon"><CalendarDays size={20}/></span><div className="portal-list-copy"><strong>{l.title}</strong><small>{l.course_title} • {dateTimeLabel(l.starts_at)}</small></div><div className="portal-list-action"><Link className="portal-soft-btn" to={'/lesson/'+l.id}><Video size={15}/> الفصل</Link>{Date.parse(l.starts_at)>Date.now()&&<button className="portal-soft-btn" onClick={()=>{setForm({id:l.id,title:l.title,starts_at:toLocal(l.starts_at),duration_minutes:l.duration_minutes});setModal('editLesson')}}><Edit3 size={14}/> تعديل</button>}</div></div>)}</div>:<PanelEmpty title="لا توجد حصص مجدولة" description="اختر دورة لإضافة حصة جديدة" icon={CalendarDays}/>;
 return <PortalShell variant="teacher" user={user} nav={nav} active={tab} onNavigate={setTab} title={labels[tab]} subtitle={descriptions[tab]} toolbar={tab==='courses'?<button className="portal-primary-btn" onClick={()=>{setForm({...fields});setModal('course')}}><Plus size={17}/> كورس جديد</button>:<button className="portal-soft-btn" onClick={load}>تحديث البيانات</button>}>
  {error&&<div className="portal-alert" role="alert">{error}<button onClick={load}>إعادة المحاولة</button></div>}
  {!data?<div className="portal-loading">جارٍ تجهيز لوحة المعلم...</div>:<>
   {tab==='overview'&&<>
    <div className="portal-teacher-banner"><div><span>مساحة التدريس • MRS SOFIA</span><h2>كل درس ممكن يكون بداية اكتشاف جديد</h2><p>جاهز تشرح، تتابع طلابك، وتبني رحلة تعلم منظمة؟</p><button onClick={()=>setTab('schedule')}>مواعيد حصصك <ArrowLeft size={17}/></button></div><Presentation size={87}/></div>
    <div className="portal-metrics"><Metric icon={BookOpen} label="كورساتك" value={courses.length} sub="تحت إشرافك"/><Metric icon={Users} label="طلابك المسجلون" value={studentCount} sub="طلاب فريدون" tone="green"/><Metric icon={CalendarDays} label="الحصص القادمة" value={upcoming.length} sub="موعد مجدول" tone="blue"/><Metric icon={ClipboardList} label="طلبات معلقة" value={pending.length} sub="تنتظر مراجعتك" tone="orange"/></div>
    <div className="portal-two-col"><section className="portal-panel"><PanelHeading title="الحصص القادمة" description="أقرب مواعيد التدريس" action={<button className="portal-text-button" onClick={()=>setTab('schedule')}>كل المواعيد <ArrowLeft size={15}/></button>}/>{lessonView(upcoming.slice(0,4))}</section>
    <section className="portal-panel"><PanelHeading title="طلبات تحتاج مراجعة" description="طلاب ينتظرون الموافقة" action={<button className="portal-text-button" onClick={()=>setTab('bookings')}>كل الطلبات <ArrowLeft size={15}/></button>}/>{bookingView(pending.slice(0,4))}</section></div>
   </>}
   {tab==='courses'&&<section className="portal-panel"><PanelHeading title="الدورات التي تديرها" description="يمكنك إنشاء دورة وإضافة حصص لها أو تعديل بياناتها"/>{courses.length?<div className="portal-table-scroll"><table className="portal-table"><thead><tr><th>الكورس</th><th>المادة والمرحلة</th><th>الطلاب</th><th>السعر</th><th>الإجراءات</th></tr></thead><tbody>{courses.map(c=><tr key={c.id}><td><strong>{c.title}</strong><small>{c.description?.slice(0,95)}</small></td><td>{c.subject} • {c.level}</td><td>{c.enrolled} / {c.capacity}</td><td>{Number(c.price).toLocaleString('ar-EG')} ج.م</td><td><div className="teacher-row-actions"><button className="portal-soft-btn" onClick={()=>{setForm({...c});setModal('editCourse')}}>تعديل</button><button className="portal-soft-btn" onClick={()=>{setForm(newLesson(c));setModal('lesson')}}>إضافة حصة</button></div></td></tr>)}</tbody></table></div>:<PanelEmpty title="لم تُنشئ كورسات بعد" description="اضغط كورس جديد عشان تضيف أول كورس علوم لك"/>}</section>}
   {tab==='students'&&<section className="portal-panel"><PanelHeading title="الطلاب المقبولون" description={'لديك '+studentCount+' طالباً مسجلاً في دوراتك'}/><label className="teacher-student-search"><Search size={18}/><input aria-label="البحث بين الطلاب" placeholder="ابحث بالاسم أو البريد أو اسم الكورس" value={search} onChange={e=>setSearch(e.target.value)}/></label>{studentBookings.length?<div className="portal-table-scroll"><table className="portal-table"><thead><tr><th>الطالب</th><th>البريد الإلكتروني</th><th>الكورس</th><th>حالة الحجز</th></tr></thead><tbody>{studentBookings.map(b=><tr key={b.id}><td><strong>{b.student_name}</strong></td><td>{b.student_email}</td><td>{b.course_title}</td><td><StatusPill status={b.status}/></td></tr>)}</tbody></table></div>:<PanelEmpty title="لا يوجد طلاب مطابقون" description="سيظهر الطلاب هنا بعد الموافقة على حجوزاتهم"/>}</section>}
   {tab==='bookings'&&<section className="portal-panel"><PanelHeading title="طلبات الحجز" description="تؤثر الموافقة على صلاحية الطالب في دخول الحصص"/>{bookingView(bookings)}</section>}
   {tab==='schedule'&&<section className="portal-panel"><PanelHeading title="جدول حصصك" description="المواعيد تعرض بتوقيت القاهرة"/>{lessonView(lessons)}</section>}
   {tab==='attendance'&&<section className="portal-panel"><Suspense fallback={<div className="portal-loading">جارٍ تحميل الحضور...</div>}><AttendancePanel courses={courses}/></Suspense></section>}
   {tab==='profile'&&<section className="portal-panel portal-form-panel"><PanelHeading title="بيانات المعلم" description="اسمك سيظهر للطلاب داخل الكورسات"/><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const r=await json('/my/profile',{method:'PATCH',body:JSON.stringify({name})});setUser(r.user);show('تم تحديث بياناتك بنجاح')}catch(e){setError(e.message)}finally{setBusy(false)}}}><label>الاسم المعروض<input value={name} maxLength={80} required onChange={e=>setName(e.target.value)}/></label><label>البريد الإلكتروني<input value={user.email} disabled/></label><label>التخصص<input value={user.specialty||'علوم'} disabled/></label><button type="submit" disabled={busy} className="portal-primary-btn"><Save size={17}/> {busy?'جارٍ الحفظ...':'حفظ بياناتي'}</button></form></section>}
  </>}
  {modal&&<div className="portal-modal-overlay" onClick={()=>setModal('')}><div className="portal-modal" onClick={e=>e.stopPropagation()}><div className="portal-panel-heading"><h2>{modal==='course'?'إنشاء كورس جديد':modal==='editCourse'?'تعديل الكورس':modal==='lesson'?'إضافة حصة':'تعديل الحصة'}</h2><button type="button" className="portal-close" onClick={()=>setModal('')}>✕</button></div>
   <form onSubmit={e=>{e.preventDefault();const course=modal==='course'||modal==='editCourse';const endpoint=course?(modal==='course'?'/courses':'/courses/'+form.id):(modal==='lesson'?'/courses/'+form.course_id+'/lessons':'/lessons/'+form.id);const values=course?{title:form.title,description:form.description,subject:form.subject,level:form.level,price:Number(form.price),capacity:Number(form.capacity),duration_minutes:Number(form.duration_minutes)}:{title:form.title,starts_at:new Date(form.starts_at).toISOString(),duration_minutes:Number(form.duration_minutes)};act(endpoint,modal.startsWith('edit')?'PATCH':'POST',values)}}>
    {(modal==='course'||modal==='editCourse')&&<>
     <label>اسم الكورس<input required maxLength={160} value={form.title||''} onChange={e=>setForm({...form,title:e.target.value})}/></label>
     <label>وصف الكورس<textarea required maxLength={2000} value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label>
     <div className="portal-form-grid"><label>المادة<input required maxLength={120} value={form.subject||''} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>المرحلة<input required maxLength={120} value={form.level||''} onChange={e=>setForm({...form,level:e.target.value})}/></label></div>
     <div className="portal-form-grid"><label>السعر بالجنيه<input required type="number" min="0" value={form.price??0} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>عدد المقاعد<input required type="number" min="1" max="500" value={form.capacity??20} onChange={e=>setForm({...form,capacity:e.target.value})}/></label></div>
    </>}
    {(modal==='lesson'||modal==='editLesson')&&<><label>عنوان الحصة<input required maxLength={160} value={form.title||''} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>موعد الحصة<input required type="datetime-local" value={form.starts_at||''} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label></>}
    <label>المدة بالدقائق<input required type="number" min="15" max="240" value={form.duration_minutes??60} onChange={e=>setForm({...form,duration_minutes:e.target.value})}/></label>
    <button type="submit" disabled={busy} className="portal-primary-btn">{busy?'جارٍ الحفظ...':'حفظ التغييرات'}</button>
   </form>
  </div></div>}
 </PortalShell>;
}
